/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as AdminLojaRouteImport } from './routes/admin.loja'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as LojaSlugIndexRouteImport } from './routes/loja.$slug.index'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin.produtos.index'
import { Route as LojaSlugCarrinhoRouteImport } from './routes/loja.$slug.carrinho'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin.produtos.novo'
import { Route as AdminProdutosIdRouteImport } from './routes/admin.produtos.$id'
import { Route as LojaSlugProdutoProductIdRouteImport } from './routes/loja.$slug.produto.$productId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLojaRoute = AdminLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const LojaSlugIndexRoute = LojaSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LojaSlugRoute,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AdminRoute,
} as any)
const LojaSlugCarrinhoRoute = LojaSlugCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => LojaSlugRoute,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/produtos/novo',
  path: '/produtos/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const LojaSlugProdutoProductIdRoute =
  LojaSlugProdutoProductIdRouteImport.update({
    id: '/produto/$productId',
    path: '/produto/$productId',
    getParentRoute: () => LojaSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/loja': typeof AdminLojaRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/loja/$slug/carrinho': typeof LojaSlugCarrinhoRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/loja/$slug/': typeof LojaSlugIndexRoute
  '/loja/$slug/produto/$productId': typeof LojaSlugProdutoProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/loja': typeof AdminLojaRoute
  '/admin': typeof AdminIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/loja/$slug/carrinho': typeof LojaSlugCarrinhoRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
  '/loja/$slug': typeof LojaSlugIndexRoute
  '/loja/$slug/produto/$productId': typeof LojaSlugProdutoProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/loja': typeof AdminLojaRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/loja/$slug/carrinho': typeof LojaSlugCarrinhoRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/loja/$slug/': typeof LojaSlugIndexRoute
  '/loja/$slug/produto/$productId': typeof LojaSlugProdutoProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/categorias'
    | '/admin/loja'
    | '/loja/$slug'
    | '/admin/'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/loja/$slug/carrinho'
    | '/admin/produtos/'
    | '/loja/$slug/'
    | '/loja/$slug/produto/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/categorias'
    | '/admin/loja'
    | '/admin'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/loja/$slug/carrinho'
    | '/admin/produtos'
    | '/loja/$slug'
    | '/loja/$slug/produto/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/categorias'
    | '/admin/loja'
    | '/loja/$slug'
    | '/admin/'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/loja/$slug/carrinho'
    | '/admin/produtos/'
    | '/loja/$slug/'
    | '/loja/$slug/produto/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  LojaSlugRoute: typeof LojaSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/loja': {
      id: '/admin/loja'
      path: '/loja'
      fullPath: '/admin/loja'
      preLoaderRoute: typeof AdminLojaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loja/$slug/': {
      id: '/loja/$slug/'
      path: '/'
      fullPath: '/loja/$slug/'
      preLoaderRoute: typeof LojaSlugIndexRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loja/$slug/carrinho': {
      id: '/loja/$slug/carrinho'
      path: '/carrinho'
      fullPath: '/loja/$slug/carrinho'
      preLoaderRoute: typeof LojaSlugCarrinhoRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loja/$slug/produto/$productId': {
      id: '/loja/$slug/produto/$productId'
      path: '/produto/$productId'
      fullPath: '/loja/$slug/produto/$productId'
      preLoaderRoute: typeof LojaSlugProdutoProductIdRouteImport
      parentRoute: typeof LojaSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminLojaRoute: typeof AdminLojaRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminLojaRoute: AdminLojaRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LojaSlugRouteChildren {
  LojaSlugCarrinhoRoute: typeof LojaSlugCarrinhoRoute
  LojaSlugIndexRoute: typeof LojaSlugIndexRoute
  LojaSlugProdutoProductIdRoute: typeof LojaSlugProdutoProductIdRoute
}

const LojaSlugRouteChildren: LojaSlugRouteChildren = {
  LojaSlugCarrinhoRoute: LojaSlugCarrinhoRoute,
  LojaSlugIndexRoute: LojaSlugIndexRoute,
  LojaSlugProdutoProductIdRoute: LojaSlugProdutoProductIdRoute,
}

const LojaSlugRouteWithChildren = LojaSlugRoute._addFileChildren(
  LojaSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  LojaSlugRoute: LojaSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
